In [20]:
import pandas as pd
import numpy as np

In [21]:
ds = pd.read_csv('banknote-authentication_csv.csv');
ds.head()

V1      V2      V3       V4  Class
0  3.62160  8.6661 -2.8073 -0.44699      1
1  4.54590  8.1674 -2.4586 -1.46210      1
2  3.86600 -2.6383  1.9242  0.10645      1
3  3.45660  9.5228 -4.0112 -3.59440      1
4  0.32924 -4.4552  4.5718 -0.98880      1

In [22]:
from sklearn.model_selection import train_test_split
X = ds.iloc[:,0:4]
Y = ds.iloc[:,4]
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,random_state=0,test_size=0.2)


In [23]:
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler();
X_train = sc_X.fit_transform(X_train);
X_test = sc_X.transform(X_test);

In [24]:
X_test

array([[-0.77000464, -2.18217308,  2.08030018,  0.08130195],
       [ 1.65638872, -0.32963963, -0.24955469,  1.09660204],
       [-0.85562469,  0.31202402, -0.78293531, -1.301957  ],
       ...,
       [-0.90845183,  0.19704581, -0.89473831, -0.59885426],
       [ 0.02407911,  0.29131655, -1.3598972 , -1.26353714],
       [-1.68223069,  0.72303272, -0.19163475, -2.05646189]])

In [25]:
from sklearn.naive_bayes import GaussianNB
cls = GaussianNB()
cls.fit(X_train,Y_train)

GaussianNB()

In [26]:
Y_pred = cls.predict(X_test)
Y_pred

array([2, 1, 2, 1, 1, 2, 2, 1, 2, 2, 1, 1, 2, 1, 1, 1, 2, 1, 1, 1, 2, 1,
       1, 2, 2, 1, 1, 2, 1, 1, 2, 2, 2, 2, 2, 1, 1, 2, 1, 2, 2, 2, 1, 2,
       2, 2, 1, 1, 2, 1, 1, 2, 2, 2, 2, 1, 2, 2, 2, 2, 1, 1, 2, 1, 1, 2,
       2, 2, 1, 1, 1, 1, 2, 2, 1, 2, 1, 1, 1, 1, 2, 2, 1, 1, 2, 2, 1, 1,
       1, 1, 1, 2, 2, 1, 2, 1, 1, 1, 2, 2, 1, 2, 1, 2, 1, 2, 1, 2, 2, 2,
       1, 2, 1, 1, 2, 1, 1, 1, 2, 2, 1, 1, 2, 2, 1, 2, 1, 1, 1, 2, 1, 1,
       1, 1, 1, 2, 1, 1, 1, 1, 2, 1, 2, 2, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1,
       2, 1, 1, 1, 2, 2, 1, 2, 2, 2, 1, 2, 2, 1, 2, 2, 1, 2, 2, 1, 2, 1,
       1, 1, 2, 1, 1, 2, 2, 1, 1, 2, 1, 2, 2, 1, 1, 1, 1, 2, 2, 1, 1, 1,
       2, 1, 1, 1, 1, 1, 2, 2, 1, 1, 1, 1, 1, 2, 1, 1, 1, 2, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 2, 1, 1, 2, 1, 2, 2, 2, 1, 2, 1, 1, 1, 2, 2, 1, 2,
       2, 1, 2, 1, 1, 2, 1, 1, 2, 2, 2, 2, 2, 1, 1, 1, 2, 1, 1, 1, 1, 2,
       1, 1, 2, 1, 1, 2, 2, 1, 2, 1, 2], dtype=int64)

In [27]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(Y_test,Y_pred)
cm

array([[134,  23],
       [ 23,  95]], dtype=int64)

In [28]:
from sklearn.metrics import accuracy_score
print(accuracy_score(Y_test,Y_pred))

0.8327272727272728
